// <auto-generated />
using System;
using Descartes.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Descartes.Migrations
{
    [DbContext(typeof(DescartesContext))]
    partial class DescartesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Descartes.Persistence.Data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("DataInserts");
                });

            modelBuilder.Entity("Descartes.Persistence.DataPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FirstId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("PairingResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirstId");

                    b.HasIndex("SecondId");

                    b.ToTable("DataPairs");
                });

            modelBuilder.Entity("Descartes.Persistence.DataPair", b =>
                {
                    b.HasOne("Descartes.Persistence.Data", "First")
                        .WithMany("PairedToAsFirst")
                        .HasForeignKey("FirstId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Descartes.Persistence.Data", "Second")
                        .WithMany("PairedToAsSecond")
                        .HasForeignKey("SecondId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("First");

                    b.Navigation("Second");
                });

            modelBuilder.Entity("Descartes.Persistence.Data", b =>
                {
                    b.Navigation("PairedToAsFirst");

                    b.Navigation("PairedToAsSecond");
                });
#pragma warning restore 612, 618
        }
    }
}
